### ISSUE TITLE
HaystackBale serialization not working with PostgreSql

### ISSUE THREAD

**Issue by blazpezdir** [Sammyjo20/laravel-haystack#61]
Laravel Version: v8.83.23
PHP Version: 8.1.12
Database Driver & Version: PostgreSQL 12.4

A serialized object in PHP that has null values before private/protected fields will fail to serialize because Postgres PDO serialization will stop on null values.
Example:
`"O:1:"A":1:{s:8:"\0*\0field";N;}"`

We can use base64_encode before inserting & base64_decode after fetching the serialized objects.

The laravel team had the same issue for batches feature
https://github.com/laravel/framework/issues/36061

**Comment by blazpezdir** [comment]
This is the solution Laravel team implemented

https://github.com/laravel/framework/pull/36081/files

**Comment by blazpezdir** [comment]
Fix is provided in pull request #63

**Comment by kristijanSC** [comment]
Having the same issue with PostgreSql. Looks like pull #60 and pull #63 ended in status quo since none is merged to core. Would you @Sammyjo20 consider merging this one to core and I can help with adjusting pull #60 afterwards?

**Comment by ksimenic** [comment]
Having the same issue with PostgreSql. Looks like pull https://github.com/Sammyjo20/laravel-haystack/pull/60 and pull https://github.com/Sammyjo20/laravel-haystack/pull/63 ended in status quo since none is merged to core. Would you @Sammyjo20 consider merging this one to core and I can help with adjusting pull https://github.com/Sammyjo20/laravel-haystack/pull/60 afterwards?

**Comment by Sammyjo20** [comment]
Hey, sorry about the slowness on this issue/PR - thank you @ksimenic for consolidating the PRs, I will take a look now!

**Comment by Sammyjo20** [comment]
This is fixed in v0.12!
